project_name: restui

before:
  hooks:
    - go mod tidy

builds:
  - id: restui
    main: .
    binary: restui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    format: tar.gz
    name_template: "restui_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: arfadmuzali
    name: restui

brews:
  - name: restui
    description: "API client in your terminal"
    homepage: "https://github.com/arfadmuzali/restui"
    repository:
      owner: arfadmuzali
      name: homebrew-restui
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    install: |
      bin.install "restui"
